version: '2'
services:
  postgres:
    build: ./script/postgresql
    command: postgres -c ssl=on
    ports:
      - "5432:5432"

  mysql:
    build: ./script/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true