create user 'mysql_async'@'%';
create user 'mysql_async_old'@'%';
create user 'mysql_async_nopw'@'%';
create database mysql_async_tests;
create table mysql_async_tests.transaction_test (id varchar(255) not null, primary key (id));
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async_old'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'mysql_async_old'@'%' = PASSWORD('do_not_use_this');
flush privileges;
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async_nopw'@'%' WITH GRANT OPTION;